### ISSUE TITLE
Elaborar fluxo de atividades do processo, em BPMN

### ISSUE THREAD

**Issue by rodrigor** [sprintcampus/processos#1]

**Comment by jabomgo** [comment]
Primeira versão do markdown feita

**Comment by jabomgo** [comment]
Grupo: Jonathan Neves, Thiago Ruan, Thiago Raimundo e Cidy Wallace

**Comment by rodrigor** [comment]
Avaliação do resultado intermediário: 10.0

**Comment by jabomgo** [comment]
# Para fazer

- [x] - Mudar a forma de mostrar as imagens BPMN (para nao ficar com as linhas indo para o além)
- [x] - Organizar melhor os diagramas
- [x] - Revisar texto (erros de portugues)
